name: "Chromatic Deployment"

on: push

jobs:
    cicd:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
