name: "Chromatic Deployment"

on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout
            - name: Checkout
              uses: actions/checkout@v1

            # Node Setup
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"

            # Install dependencies
            - name: Install dependencies
              run: npm install

            # Build Storybook
            - name: Build Storybook
              run: npm run build-storybook -- --output-dir=storybook-static

            # Deploy
            - name: Deploy
              uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

            # Message
            - name: Comment PR
              uses: thollander/actions-comment-pull-request@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.PERSONNAL_TOKEN }}
              with:
                  message: "storybook deploy: ${{ steps.chromatic.outputs.storybookUrl}}"
